package top.osjf.cron.core.repository;

import top.osjf.commons.lang.Nullable;
import top.osjf.commons.util.Assert;
import top.osjf.cron.core.exception.CronInternalException;

import java.util.concurrent.atomic.AtomicBoolean;

public class CronTaskBuilder implements CronTaskRepository.Builder {

    private final CronTaskRepository repository;

    // Required parameters
    private String expression;
    private Object taskBody;

    // Optional governance parameters
    @Nullable
    private Integer maxRunTimes;

    @Nullable
    private RunningTimeout runningTimeout;

    /** Mark to ensure build() only execute once for current builder instance. */
    private final AtomicBoolean built = new AtomicBoolean(false);

    /**
     * Private constructor, use {@link #forRepository(CronTaskRepository)} to create builder instance.
     *
     * @param repository target cron task repository for task registration, must not be {@code null}
     */
    private CronTaskBuilder(CronTaskRepository repository) {
        Assert.notNull(repository, "CronTaskRepository must not be null");
        this.repository = repository;
    }

    /**
     * Create a new {@code CronTaskBuilder} bound to specified {@link CronTaskRepository}.
     *
     * @param repository task repository instance
     * @return fluent builder instance
     */
    public static CronTaskBuilder forRepository(CronTaskRepository repository) {
        return new CronTaskBuilder(repository);
    }

    /**
     * Set cron trigger expression.
     *
     * @param expression valid cron expression
     * @return current builder instance for chained call
     */
    @Override
    public CronTaskBuilder withExpression(String expression) {
        this.expression = expression;
        return this;
    }

    /**
     * Set task execution body with raw {@link Runnable}.
     *
     * @param runnable task runnable
     * @return current builder instance for chained call
     */
    @Override
    public CronTaskBuilder withTask(Runnable runnable) {
        this.taskBody = runnable;
        return this;
    }

    /**
     * Set task execution body with {@link CronMethodRunnable}.
     *
     * @param methodRunnable method wrapped runnable
     * @return current builder instance for chained call
     */
    @Override
    public CronTaskBuilder withTask(CronMethodRunnable methodRunnable) {
        this.taskBody = methodRunnable;
        return this;
    }

    /**
     * Set task execution body with {@link RunnableTaskBody}.
     *
     * @param runnableTaskBody runnable task wrapper
     * @return current builder instance for chained call
     */
    @Override
    public CronTaskBuilder withTask(RunnableTaskBody runnableTaskBody) {
        this.taskBody = runnableTaskBody;
        return this;
    }

    /**
     * Set task execution body with generic {@link TaskBody}.
     *
     * @param taskBody generic task wrapper
     * @return current builder instance for chained call
     */
    @Override
    public CronTaskBuilder withTask(TaskBody taskBody) {
        this.taskBody = taskBody;
        return this;
    }

    /**
     * Set task execution body with complete {@link CronTask}.
     *
     * @param cronTask full cron task metadata
     * @return current builder instance for chained call
     */
    @Override
    public CronTaskBuilder withTask(CronTask cronTask) {
        this.taskBody = cronTask;
        return this;
    }

    /**
     * Enable limited execution times governance.
     * The task will be automatically unregistered after reaching the maximum execution count.
     *
     * @param maxTimes maximum allowed execution count, must greater than 0
     * @return current builder instance for chained call
     */
    @Override
    public CronTaskBuilder limitRunTimes(int maxTimes) {
        Assert.isTrue(maxTimes > 0, "Max run times must be greater than 0");
        this.maxRunTimes = maxTimes;
        return this;
    }

    /**
     * Enable task execution timeout governance.
     * The running task will be interrupted if execution exceeds the configured duration.
     *
     * @param timeout task timeout config
     * @return current builder instance for chained call
     */
    @Override
    public CronTaskBuilder timeout(RunningTimeout timeout) {
        this.runningTimeout = timeout;
        return this;
    }

    /**
     * Perform parameter validation, match the corresponding overloaded registration method according to the configured parameters,
     * complete the task registration, and return the globally unique task ID generated by the repository.
     * <p>This method can only be called once per builder instance. Repeated call will throw {@link IllegalStateException}.
     *
     * @return registered globally unique task ID
     * @throws IllegalStateException    if build() method is called repeatedly
     * @throws IllegalArgumentException if required cron expression or task body is missing, or unsupported task body type
     * @throws CronInternalException    if underlying repository throws exception during task registration
     */
    public String build() {
        // Prevent repeated build call for current builder instance
        Assert.state(built.compareAndSet(false, true),
                "The current CronTaskBuilder instance can only call build() once, please create a new builder for new task registration.");

        // Global parameter validity check
        Assert.hasText(expression, "Cron expression must be specified");
        Assert.notNull(taskBody, "Task execution body must be specified");

        String taskId;

        // Scenario 1: Register by integrated CronTask object
        if (taskBody instanceof CronTask) {
            CronTask cronTask = (CronTask) taskBody;
            if (maxRunTimes != null && runningTimeout != null) {
                taskId = repository.registerRunTimes(cronTask, maxRunTimes, runningTimeout);
            } else if (maxRunTimes != null) {
                taskId = repository.registerRunTimes(cronTask, maxRunTimes);
            } else if (runningTimeout != null) {
                taskId = repository.register(cronTask, runningTimeout);
            } else {
                taskId = repository.register(cronTask);
            }
        } else {
            // Scenario 2: Register with cron expression + various raw task body types
            if (maxRunTimes != null && runningTimeout != null) {
                if (taskBody instanceof Runnable) {
                    taskId = repository.registerRunTimes(expression, (Runnable) taskBody, maxRunTimes, runningTimeout);
                } else if (taskBody instanceof CronMethodRunnable) {
                    taskId = repository.registerRunTimes(expression, (CronMethodRunnable) taskBody, maxRunTimes, runningTimeout);
                } else if (taskBody instanceof RunnableTaskBody) {
                    taskId = repository.registerRunTimes(expression, (RunnableTaskBody) taskBody, maxRunTimes, runningTimeout);
                } else if (taskBody instanceof TaskBody) {
                    taskId = repository.registerRunTimes(expression, (TaskBody) taskBody, maxRunTimes, runningTimeout);
                } else {
                    throw new IllegalArgumentException("Unsupported task body type: " + taskBody.getClass().getName());
                }
            } else if (maxRunTimes != null) {
                if (taskBody instanceof Runnable) {
                    taskId = repository.registerRunTimes(expression, (Runnable) taskBody, maxRunTimes);
                } else if (taskBody instanceof CronMethodRunnable) {
                    taskId = repository.registerRunTimes(expression, (CronMethodRunnable) taskBody, maxRunTimes);
                } else if (taskBody instanceof RunnableTaskBody) {
                    taskId = repository.registerRunTimes(expression, (RunnableTaskBody) taskBody, maxRunTimes);
                } else if (taskBody instanceof TaskBody) {
                    taskId = repository.registerRunTimes(expression, (TaskBody) taskBody, maxRunTimes);
                } else {
                    throw new IllegalArgumentException("Unsupported task body type: " + taskBody.getClass().getName());
                }
            } else if (runningTimeout != null) {
                if (taskBody instanceof Runnable) {
                    taskId = repository.register(expression, (Runnable) taskBody, runningTimeout);
                } else if (taskBody instanceof CronMethodRunnable) {
                    taskId = repository.register(expression, (CronMethodRunnable) taskBody, runningTimeout);
                } else if (taskBody instanceof RunnableTaskBody) {
                    taskId = repository.register(expression, (RunnableTaskBody) taskBody, runningTimeout);
                } else if (taskBody instanceof TaskBody) {
                    taskId = repository.register(expression, (TaskBody) taskBody, runningTimeout);
                } else {
                    throw new IllegalArgumentException("Unsupported task body type: " + taskBody.getClass().getName());
                }
            } else {
                if (taskBody instanceof Runnable) {
                    taskId = repository.register(expression, (Runnable) taskBody);
                } else if (taskBody instanceof CronMethodRunnable) {
                    taskId = repository.register(expression, (CronMethodRunnable) taskBody);
                } else if (taskBody instanceof RunnableTaskBody) {
                    taskId = repository.register(expression, (RunnableTaskBody) taskBody);
                } else if (taskBody instanceof TaskBody) {
                    taskId = repository.register(expression, (TaskBody) taskBody);
                } else {
                    throw new IllegalArgumentException("Unsupported task body type: " + taskBody.getClass().getName());
                }
            }
        }

        // Unified post-processing: log, metrics can be added here
        return taskId;
    }
}