<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.osjf.cron</groupId>
        <artifactId>assembly-simplified-cron</artifactId>
        <version>3.0.1-GA</version>
    </parent>

    <artifactId>cron-datasource-driven-scheduled-serialization</artifactId>
    <packaging>jar</packaging>
    <name>cron-datasource-driven-scheduled-serialization ${project.version}</name>
    <description>Read deserialization and modify serialization for storing timed task information components.</description>

    <properties>
        <xstream.version>1.4.20</xstream.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>top.osjf.cron</groupId>
            <artifactId>cron-datasource-driven-scheduled</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>

        <dependency>
            <groupId>com.thoughtworks.xstream</groupId>
            <artifactId>xstream</artifactId>
            <version>${xstream.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>

    </dependencies>

</project>