package top.osjf.assembly.simplified.aop;

/**
 * The interface definition during the method execution phase
 * comes from AOP support and is consistent with Aspectj's
 * interception and parsing.
 *
 * @see StepInterceptor
 * @author <a href="mailto:929160069@qq.com">zhangpengfei</a>
 * @since 2024.05.10
 */
public interface Step {

    /**
     * Execute the target method before execution.
     */
    default void before() {
    }

    /**
     * Execute after the target method returns.
     * @param result results of enforcement.
     */
    default void afterReturn(Object result) {
    }

    /**
     * Execute after the target method exception.
     * @param e The exception generated by the execution of the target method.
     */
    default void afterThrow(Throwable e) {
    }

    /**
     * After the target method is executed, it is ultimately executed.
     */
    default void after() {
    }
}
